name: pages-build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Generate Environment File From GitHub Secrets
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: node github-generate-environment.js
        env:
          ENVIRONMENT: '${{ secrets.ENVIRONMENT }}'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Build App
        working-directory: ./
        run: npm run build:pro && cp dist/personal-web/browser/index.html dist/personal-web/browser/404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/personal-web/browser # The folder the action should deploy.
