name: pages-build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: node server.js
        env:
          ENVIROMENT: '${{ secrests.ENVIROMENT }}'

      - name: Install and build
        working-directory: ./
        run: npm install && npm run build:pro && cp dist/personal-web/index.html dist/personal-web/404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/personal-web # The folder the action should deploy.
