name: pages-build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Generate environment file from github secrets
        run: node github-generate-environment.js
        env:
          ENVIRONMENT: '${{ secrets.ENVIRONMENT }}'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Build app
        working-directory: ./
        run: npm run build:pro && cp dist/personal-web/browser/index.html dist/personal-web/browser/404.html

      - name: Deploy to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/personal-web/browser # The folder the action should deploy.
